### ISSUE TITLE
Printing out SVG

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [restlessminded/dokuwiki-plugin-svgEmbed#1]
Hi,

when printing a page with SVG file, the SVG image is greatly reduced in size.

Best regards
Juergen

**Comment by restlessminded** [comment]
What browser are you using? Are you setting width and height on the images? I don't
have the problem with scaling when printing if I set a width and height on the image in
Chrome or Firefox.

Example:

  `{{ :user:briar-keep-2018.svg?396x306 |}}`

Just like for any other image.

**Comment by restlessminded** [comment]
I think the latest commits fix this issue because now sizes are explicitly embedded into the definition.  It scales properly on render under the latest Chrome and Firefox under Windows 7 x64 and Windows 10 Enterprise x64, as well as Chrome on Android P.  Please update and verify.

**Comment by Juergen-aus-Koeln** [comment]
Very good, now it works.
Thank you very much!

**Comment by restlessminded** [comment]
Glad it's fixed!  Happy to help!
