### ISSUE TITLE
Instead of showing, my SVGs download themselves

### ISSUE THREAD

**Issue by Kinboise** [restlessminded/dokuwiki-plugin-svgEmbed#11]
## What I expect:
- Without svgEmbed, `.svg` files are shown as images;
- With svgEmbed, `.svg` files are shown as embed or object.

## What I get:
- Without svgEmbed, `.svg` files are not shown, and nothing happens;
- With svgEmbed, `.svg` files are not shown, Edge automatically downloads the `.svg` file for me, and Firefox does nothing.

What could be the problem? I'm using Windows Server 2019, PHP 7.3.4 NTS, Apache 2.4.39, DokuWiki "Hogfather", default template.

Thanks!

**Comment by restlessminded** [comment]
If it's not showing as image files without the plugin it sounds like your server doesn't correctly send the content type of SVG files.  You may need to configure the server to send the right content type.

I suspect once it works without the plugin it will work with it as well.

**Comment by Kinboise** [comment]
Sorry it was my fault, I've been stupid to put that `svg     image/svg+xml` line in a wrong file. Can't believe I spent my whole day trying to fix it. Thanks a lot!
