### ISSUE TITLE
SVG doesn't show but offers download

### ISSUE THREAD

**Issue by gatonero** [restlessminded/dokuwiki-plugin-svgEmbed#14]
In every page I embed a SVG file it isn't shown but shows an option to download it. You can see this behavior 
https://drive.google.com/file/d/18vIO7LfBeGz2bu5C207EllOpjRiVme8-/view?usp=sharing

**Comment by restlessminded** [comment]
See #11 and see if that helps.  That's likely the problem.

**Comment by gatonero** [comment]
Thanks a lot! Problem is solved. :-)
