### ISSUE TITLE
I can't activate svgEmbed 

### ISSUE THREAD

**Issue by Big-bros** [restlessminded/dokuwiki-plugin-svgEmbed#15]
Hi, I have installe svgEmbed on dokuwiki.
When I go to the admin page,, i can see the plugin, i can press the "activate" button but nothing happens. Well, the button changes but it doesn't seem to activate anything (and if i come back on the admin page, it is still desactivated)
I tried to put $conf['svGembed'] = 1 manually but nothing happens.
My dokuwiki version is "Release 2022-07-31 Igor"

**Comment by restlessminded** [comment]
How did you install it?

When I go to the Extension Manager I don't see any "activate" buttons, I see "Enable" or "Disable".  Are we talking about the same thing?

![image](https://user-images.githubusercontent.com/52088098/187801704-fb537d76-2a4e-4f23-98b8-5c6d68fb422f.png)

**Comment by Big-bros** [comment]
I installed it manually (copying the files in the plugin directory under svgEmbed) (because i have this error but it is not the subject here :-)
![image](https://user-images.githubusercontent.com/53227593/187877437-d5536226-26cb-4612-90bc-b01af7fd8575.png)

In my extension manager, i can see svgEmbed
![image](https://user-images.githubusercontent.com/53227593/187877822-638d510e-0fda-419e-9453-a1457c4ad33a.png)

but if i click "enable", the button label toggles to disable but in fact, nothing happens. If i refresh the page, the button label is back to "enable" and my svg files are still in <img> tags.

**Comment by restlessminded** [comment]
Now that one is a puzzler!

I am assuming you are running this on Linux.  Make sure that your web server has access to the directories by `chown`ing and `chmod`ing to the right user and permissions (I ran into not having the right user on a set of plugins once and having a related issue before).  Also, [check out these suggestions](https://www.dokuwiki.org/faq:pluginproblems) to see if any of them are relevant to the issue.

**Comment by restlessminded** [comment]
Also, I assume the proxy issues are because of a corporate network?  (I know how that goes; I deal with that at work, too, so I copy and install or upgrade things manually on our departmental wiki.)

**Comment by Big-bros** [comment]
> I assume the proxy issues are because of a corporate network? 
Probably, yes.

I'm not on linux... I'm on windows (10). This is just some kind of local experimentation (no one except me use it) and my computer use windows, so i don't think it's a user issue.
What i understand is that it is probably more a problem with my install of dokuwiki than with this specific plugin.
I'll try to install another plugin and see if i have the same problem...
I'll write here if i have some more info
Thanks

**Comment by Big-bros** [comment]
I reinstalled it, probably a better way... It seems to works now.

**Comment by restlessminded** [comment]
I'm glad that you got it resolved!
