### ISSUE TITLE
Suggested Feature: Print Button

### ISSUE THREAD

**Issue by lizat** [restlessminded/dokuwiki-plugin-svgEmbed#8]
Hi Michael, 
I was thinking it would be good to be able to print the SVG images. I have no idea how complex that would be to implement but it would be a great feature.

Thank you for the plug-in, it's working well

Liz

**Comment by restlessminded** [comment]
Let me cogitate on that one.  In theory it's the same as opening or creating the container for content in a new window and calling to print from there, which more or less is how the client-side print buttons work as far as I can tell.

**Comment by restlessminded** [comment]
I tried a first pass simply copying the content of the `<span>` into the body, printing and then restoring the rest of the page.  No dice.

**Comment by restlessminded** [comment]
I got something working that adds a link for printing, pops up a window and goes to the print dialog in both Firefox and Chrome (I've learned to ignore IE over the years).  In Firefox I can't get the JavaScript to close the popup window by hook or crook (I am open to suggestions!) so I just change the text to remind you to close it.

I have style up the link a bit, add a configuration option or five and all that.  I'll try my best to finish up by the end of the weekend.  (I'm trying to move into my new home office so I can stop working across the kitchen table from my wife; that'll be taking up quite a bit of my time.)

**Comment by restlessminded** [comment]
I just updated the source, documentation to come in the next couple days.

Essentially, I added a config option to make all SVG files printable by default or not, and also I added a per-SVG file parameter to print or disable printing (to print, add `&print` or `&print:on`, to disable printing per SVG, add `&print:off`).

If an SVG is printable, a "print SVG" tab should show under it.  It's ugly as sin, so you just need to style it yourself in your CSS.  I added some basic default, but you can do as you wish with it by styling the classes `.dokuwiki div.svgprintbutton_table button` and `.dokuwiki div.svgprintbutton_table:hover button`.  To change the style of the SVG file itself when the button is hovered, style `.svgembed_print_border`.

**Comment by restlessminded** [comment]
Actually, hold that thought...

**Comment by restlessminded** [comment]
Okay, try now.  I had an oversight in the upload versus my development server.  Hopefully no one downloaded it in those few minutes... heh.

**Comment by restlessminded** [comment]
I _finally_ got around to writing up the documentation at [the plugin page](https://www.dokuwiki.org/plugin:svgembed), so I will close this issue now.
